import Link from 'next/link';

export const Terms = () => (
  <section className='privacyAndTerms'>
    <div className='container'>
      <div className='row '>
        <div className='col-10 col-md-8 mx-auto'>
        <h2>Terms of Service</h2>

          <div className='article'>
            <h4>1. General</h4>
            
            <p>1.1 This is an agreement (&quot;Agreement&quot;) between you and Sway Protocol (together with our affiliates and/or subsidiaries from time to time). We provide, amongst other services, software products and applications that connect people to digital assets and web3.</p>
            <p>1.2 References in this Agreement to &quot;Sway Protocol&quot;, &quot;we&quot;, &quot;our&quot; and &quot;us&quot; are to Sway Protocol. References to &quot;you&quot; or &quot;your&quot; are to the person with whom Sway Protocol enters into this Agreement.</p>
            <p>1.3 By accessing any areas on our website (including <a className='color-main' href='https://swayprotocol.org' target='_blank' rel='noreferrer'>https://swayprotocol.org</a>), applications, marketplaces, wallets, platforms and software (collectively, &quot;Sites&quot;) and signing up of any accounts therein (where applicable), you agree that you have read, understood and accepted all the terms and conditions contained in this Agreement (&quot;Terms&quot;), save where expressly provided for specifically in each of the Sites (of which the latter shall take precedence).</p>
            <p>1.4 You should be aware that the risk of loss in trading or holding digital assets and currencies can be substantial. As with any asset, the value of digital currencies can fluctuate and there can be a substantial risk that you lose money buying, selling, holding, or investing in digital currencies and other digital assets.</p>
            <p>1.5 Sway Protocol shall only operate in jurisdictions where its Digital Currency and Assets Services (defined below) are specifically licensed.</p>
            <p>1.6 Even in jurisdictions where Sway Protocol is licensed to provide its Digital Currency and Assets Services (defined below), the said services may not necessarily be regulated by the Government and you may therefore not be protected by regulation. You should carefully consider whether trading or holding digital currencies and assets is suitable for you in light of your financial condition. Sway Protocol is not obligated to provide you with legal advice as to whether the said Services are regulated by the government of the jurisdiction that you reside in, and you should seek your own legal advice.</p>
            <p>1.7 If you download any applications through any app store distribution platform (&quot;App Provider&quot;), you acknowledge and agree that: (i) these Terms are between us, and not with the App Provider; (ii) the App Provider has no obligation to furnish maintenance and support services or handle any warranty claims; and (iii) the App Provider is not responsible for addressing any claims you or any third party have relating to the App.</p>
            <p>1.8 If you are not comfortable with any of these Terms, we would advise you to exit. By accessing any of the Sites, you are agreeing to these Terms. Please continue only if you can accept these Terms.</p>
          </div>
          <div className='article'>
            <h4>2. Eligibility</h4>
            <p>2.1 To be eligible to use any of the Digital Currency and Assets Services, you must be at least 18 years old and reside in a country in which the said services are accessible. Please note that not all Digital Currency and Assets Services are available in every country.</p>
            <p>2.2 By accessing or using the Sites, you represent and warrant that you have not previously been suspended or removed from the Sites. You represent and warrant that you are not: (a) located in, under the control of, or a national or resident of any country with embargoed goods or services. You further represent and warrant that you will not use the Sites if the laws of your country prohibit you from doing so in accordance with these Terms.</p>
          </div>
          <div className='article'>
            <h4>3. Access to the Sites</h4>
            <p>3.1 The accessibility and operation of the Sites rely on technologies outside our control. We are not able to guarantee continuous accessibility or uninterrupted operation of the Sites.</p>
          </div>
          <div className='article'>
            <h4>4. Digital Currency and Assets Services</h4>
            <p>4.1 The following services (the &quot;Digital Currency and Assets Services&quot;) may be provided to you by Sway Protocol: a. one or more hosted digital currency and assets wallets enabling you to store, track, transfer, and manage balances of certain supported digital currencies including Polygon/MATIC (the &quot;Digital Currency Wallet&quot; and &quot;Digital Currency&quot; respectively); b. one or more hosted digital wallet enabling you to store Sway Protocol Utility Tokens (SWAY tokens)); c. certain services enabling you to stake $SWAY; and d. a Digital Asset marketplace service enabling you to obtain prices for your purchases and sales of Digital Assets (NFTs), and (subject to certain restrictions) carry out any such purchases or sales on the Sites.</p>
            <p>4.2 Your Digital Currency Wallet enables you to send Digital Currency to, and request, receive, and store Digital Currency from, third parties by giving instructions through the Sites (each such transaction is a &quot;Digital Currency Transaction&quot;).</p>
          </div>
          <div className='article'>
            <h4>5. Relying on Information</h4>
            <p>5.1 We provide our websites as sources of general information only. We are not involved in giving professional advice here. The websites may not cover all information available on a particular issue. We would advise that you conduct your own checks or obtain professional advice relevant to your particular circumstances, outside of the websites.</p>
            <p>5.2 We deal on an execution only basis and do not advise on the merits of particular transactions, or their taxation consequences.</p>
            <p>5.3 Without prejudice to our foregoing obligations, in asking us to enter into any transaction, you represent that you have been solely responsible for making your own independent appraisal and investigations into the risks of the transaction. You represent that you have sufficient knowledge, market sophistication, professional advice and experience to make your own evaluation of the merits and risks of any transaction. We give you no warranty as to the suitability of the products traded under these Terms and assume no fiduciary duty in our relations with you.</p>
            <p>5.4 Where we do provide generic trading recommendations, market commentary or other information: a. this is incidental to your dealing relationship with us. It is provided solely to enable you to make your own investment decisions and does not amount to advice; b. we give no representation, warranty or guarantee as to the accuracy or completeness of such information or as to the tax consequences of any transaction.</p>
          </div>
          <div className='article'>
            <h4>6. Restrictions on Use of Materials</h4>
            <p>6.1 Unless otherwise indicated on the Sites, the Sites and all content and other materials on the Sites, including, without limitation, any logos and all designs, text, graphics, pictures, information, data, software, sound files, other files and the selection and arrangement thereof (collectively, &quot;Materials&quot;) are the proprietary property of Sway Protocol or its licensors or users and are protected.</p>
            <p>6.2 No Material from the Sites shall be reproduced, republished, uploaded, posted, transmitted or otherwise distributed in any way without our prior written consent. Graphics and images on the Sites are protected by copyright and may not be reproduced or appropriated in any manner without our prior written consent.</p>
            <p>6.3 Modification of any of the materials or use of any of the materials for any other purpose will be a violation of copyright and other intellectual property rights.</p>
            <p>6.4 The downloading of any software, including any files, images and data accompanying the software (hereinafter called &quot;the software&quot;) from the Sites by you does not in any way transfer title of the software to you. You may not redistribute, sell, de-compile, reverse-engineer or disassemble or otherwise deal with the software nor create derivative works from the Sites or the materials thereon. Any unauthorized use of the Sites or the Materials thereon is strictly prohibited.</p>
          </div>
          <div className='article'>
            <h4>7. Sites Accuracy and Third Party Content</h4>
            <p>7.1 Access to services may become degraded or unavailable during times of significant volatility or volume. This could result in the inability to buy or sell for periods of time and may also lead to support response time delays.</p>
            <p>7.2 Although we intend to provide accurate and timely information on the Sites, the Sites may not always be entirely accurate, complete or current and may also include technical inaccuracies or typographical errors.</p>
            <p>7.3 Sway Protocol and its users may provide third party content on the Sites and may provide links to web pages and content that are not owned or controlled by Sway Protocol (collectively the &quot;Third Party Content&quot;) as a service to those interested in this information.</p>
            <p>7.4 Sway Protocol does not control, endorse or adopt any Third Party Content and makes no representation or warranties of any kind regarding the Third Party Content, including without limitation regarding its accuracy or completeness.</p>
            <p>7.5 You acknowledge and agree that we are not responsible or liable in any manner for any Third Party Content and undertake no responsibility to update or review any Third Party Content. Users use such Third Party Content contained therein at their own risk. Your business dealings or correspondence with, or participation in promotions of, any third parties, and any terms, conditions, warranties or representations associated with such dealings or promotions, are solely between you and such third parties. Sway Protocol is not responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or promotions or as the result of the presence of such Third Party Content on the Site.</p>
          </div>
          <div className='article'>
            <h4>8. User Conduct and Obligations</h4>
            <p>Your access to the Sites is subject to the following restrictions and prohibitions on use. You agree that you shall not upload, post, transmit, share or otherwise make available through, or to, the Sites any content that: a. Is unlawful, abusive, threatening, harmful, obscene, lewd, offensive, defamatory, or otherwise objectionable. b. Might infringe the intellectual property rights, privacy rights, rights of publicity, or other proprietary rights of others. c. Might violate any local, federal, or international law, or any rules of any securities exchange, either intentionally or unintentionally. d. Contains any viruses, trojan horses, time bombs, cancelbots, or any other harmful or disruptive computer code, file, 
              or program designed to interrupt, destroy, or limit the functionality of any computer software or hardware or telecommunications equipment. e. Disrupt, disable, place unreasonable burdens or excessive loads on, interfere with, or attempt to gain unauthorised access to any portion of the Sites, or their computer systems, servers, or networks. f. Post or provide any information that that you know (or ought to know) is false or misleading, provide false information about yourself, impersonate any other person, or otherwise attempt to mislead others about your identity, your affiliation with any person or entity, or the origin of any content, message, or other communication. g. Upload, post, transmit, share, or otherwise 
              make available any unsolicited or unauthorised advertising, solicitations, promotional materials, &quot;junk mail&quot;, &quot;spam&quot;, &quot;chain letters&quot;, &quot;pyramid schemes&quot;, or any other form of solicitation, bulk e-mail, or duplicative messages. h. Use any automatic or manual process to collect, harvest, gather, or extract information about other visitors to or users of the Sites, or otherwise systematically extract data or data fields, including without limitation any financial and/or currency data or e-mail addresses. i. Use the Sites for the purpose of gathering information for, or transmitting, unsolicited bulk commercial e-mail over the Internet to other users of the Sites or to other third parties. Internet e-mail sent to, or through, 
              the computer systems of the Sites or to users of the Sites or to other third parties containing invalid or forged headers, invalid or non-existent domain names, or other deceptive addressing is deemed counterfeit. j. Provide access to or use of any portion of the Sites through any time sharing system, service bureau, the Internet, or any other technology now existing or developed in the future, except as specifically permitted in writing by Sway Protocol. k. Redistribute any information and content, including but not limited to financial and currency data, in any manner whatsoever including without limitation by means of printed publication, fax broadcast, web pages, e-mail, web newsgroups or forums, or any other electronic 
              or paper- based service or method, to any person, organisation, corporation or other entity, including within your own organisation or externally. l. Use any information and content, including but not limited to financial and currency data, for any purpose competitive with Sway Protocol’s businesses which include, without limitation, providing raw currency data and currency rate conversion services. m. Present, archive, cache, frame, scrape, or mirror any information and content from any part of the Sites within another web site, except with express written permission from Sway Protocol. n. Remove, obscure, or alter any notice of Sway Protocol’s intellectual property rights present on or in the Sites, including but not limited 
              to copyright, trademark, and/or patent notices. o. Copy, disassemble, decompile, translate, reverse engineer or otherwise reduce the Sites software or use any network monitoring or discovery software to determine the network and/or computer architecture, except as permitted by mandatory rules of applicable law that cannot be disapplied by contract. p. Remove, disable, defeat, or change any functionality or appearance of the Sites or intentionally alter the format in which financial and currency data is provided by Sway Protocol or otherwise circumvent the Sites’ regular interfaces to such data; and embed or import any financial and currency data provided in, on or through the Sites into any information services (whether or not web-based),
               data files, or application software, including without limitation accounting and payroll systems, except as specifically permitted in writing by Sway Protocol. q. Embed or import any financial and currency data provided in, on or through the Sites into any information services (whether or not web-based), data files, or application software, including without limitation accounting and payroll systems, except as specifically permitted in writing by Sway Protocol. r. The foregoing prohibitions expressly include, but are not limited to, the practice of &quot;screen scraping&quot;, or any other practice or activity the purpose of which is to obtain lists of data, portions of a database, or other lists or information from the Sites, in any manner or in 
               any quantities not authorised in writing by Sway Protocol.
            </p>
          </div>
          <div className='article'>
            <h4>9. Modifications to Terms and Conditions of Use</h4>
            <p>9.1 We reserve the right to change or modify the terms and conditions contained in these Terms or any policy or guideline of the Sites, at any time and in our sole discretion. We may provide notice of these changes by posting the revised Terms to the Sites and changing the &quot;Last Revised&quot; date at the top of the Terms, or by providing other means of notice as we will determine each time in our sole discretion. Using a particular form of notice in some instances does not obligate us to use the same form in other instances. Any changes or modifications will be effective immediately upon posting the revisions to the Sites, and will apply to your subsequent use of the Sites.</p>
            <p>9.2 You waive any right you may have to receive specific notice of such changes or modifications. Your continued use of this Site will confirm your acceptance of such changes or modifications; therefore, you should review the Terms and applicable policies whenever you use the Sites to understand the terms that apply to such use. The most current version of the Terms can be reviewed by clicking on the &quot;Terms of Use&quot; hypertext link located at the bottom of our web pages. If you do not agree to the Terms in effect when you access or use the Sites, you must stop using the Sites.</p>

          </div>
          <div className='article'>
            <h4>10. Limitation of Liability</h4>
            <p>10.1 If you have a dispute with one or more users of the services (other than Sway Protocol), you agree that neither we nor our affiliates, subsidiaries or service providers, nor any of our respective officers, directors, agents, joint venturers, employees and representatives, will be liable for any claims, demands and damages (actual and consequential, direct or indirect) of any kind or nature arising out of or in any way connected with such disputes.</p>
            <p>10.2 You agree to indemnify us, our affiliates, subsidiaries and service providers, and each of our, or their, respective officers, directors, agents, employees and representatives, in respect of any costs (including attorneys&quot; fees and any fines, fees or penalties imposed by any regulatory authority) that have been reasonably incurred in connection with any claims, demands or damages arising out of or related to your breach and / or our enforcement of this Agreement or your violation of any law, rule or regulation, or the rights of any third party.</p>
            <p>10.3 Sway Protocol’s total aggregate liability to you for any individual claim or series of connected claims for losses, costs, liabilities or expenses which you may suffer arising out of, or in connection with, any breach by Sway Protocol of this Agreement shall be limited to a maximum aggregate value of the combined value of the Digital Assets on deposit in your Digital Wallet at the time of the relevant claim. Where we are considering a specific claim relating to a specific transaction this sum shall be further limited to the purchase / sale amount (as relevant) of the transaction in dispute.</p>
            <p>10.4 In addition to the liability cap above, in no event shall we, our affiliates, subsidiaries or service providers, or any of our or their respective officers, directors, agents, employees or representatives, be liable for any of the following types of loss or damage arising under or in connection with this Agreement or otherwise: a. any loss of profits or loss of expected revenue or gains, including any loss of anticipated trading profits and / or any actual or hypothetical trading losses, whether direct or indirect, even if we are advised of or knew or should have known of the possibility of the same. This means, by way of example only (and without limiting the scope of the preceding sentence), that if you claim that we failed to process a buy or sell transaction properly, your damages are limited to no more than the combined value of the supported Digital Currency at issue in the transaction, and that you may not recover for any &quot;loss&quot; of anticipated trading profits or for any actual trading losses made as a result of the failure to buy or sell; b. any loss of, or damage to, reputation or goodwill; any loss of business or opportunity, customers or contracts; any loss or waste of overheads, management or other staff time; or any other loss of revenue or actual or anticipated savings, whether direct or indirect, even if we are advised of or knew or should have known of the possibility of the same; c. any loss of use of hardware, software or data and / or any corruption of data; including but not limited to any losses or damages arising out of or relating to any inaccuracy, defect or omission of digital currency price data; any error or delay in the transmission of such data; and / or any interruption in any such data; and d. any loss or damage whatsoever which does not arise directly as a result of our breach of this Agreement (whether or not you are able to prove such loss or damage).</p>
            <p>10.5 The limitation of liability in this Section 14 is subject to any obligations that we have under applicable law and regulation, including our obligation to exercise reasonable care and skill in our provision of the services. Nothing in this Agreement shall limit our liability resulting from our fraud or fraudulent misrepresentation, gross negligence, deliberate misconduct, for death or personal injury resulting from either our or our subcontractors’ negligence.</p>
            <p>10.6 The services are provided on an &quot;as is&quot; and &quot;as available&quot; basis, with no further promises made by us around availability of the services. Specifically, we do not give any implied warranties of title, merchantability, fitness for a particular purpose and/or non-infringement. We do not make any promises that access to the Sites, any of the services, or any of the materials contained therein, will be continuous, uninterrupted, timely, or error-free.</p>
            <p>10.7 We make no representations about the accuracy, order, timeliness or completeness of historical Digital Currency price data available on the Sites. We will make reasonable efforts to ensure that requests for debits and credits involving bank accounts, credit and debit cards are processed in a timely manner but we make no representations or warranties regarding the amount of time needed to complete processing which is dependent upon many factors outside of our control. We will make reasonable efforts to ensure that requests for electronic debits and credits involving bank accounts, credit cards, and cheque issuances are processed in a timely manner, but we make no representations or warranties regarding the amount of time needed to complete processing which is dependent upon many factors outside of our control.</p>
            <p>10.8 Except for the express statements set forth in this Agreement, you hereby acknowledge and agree that you have not relied upon any other statement or understanding, whether written or oral, with respect to you use and access of the services and Sites.</p>
            <p>10.9 We are not liable for any breach of the Agreement, including delays, failure in performance or interruption of service, where they arise directly or indirectly from abnormal and unforeseeable circumstances beyond our control, the consequences of which would have been unavoidable despite all effects to the contrary, nor are we liable where the breach is due to the application of mandatory legal rules.</p>
          </div>
          <div className='article'>
            <h4>11. Privacy</h4>
            <p>Your use of the Sites and our services is subject to our <Link href='/privacy'><span className='color-main'>Privacy Policy.</span></Link></p>
          </div>
          <div className='article'>
            <h4>12. Contact</h4>
            <p>12.1 If you have any feedback, questions, or complaints, contact us as provided below: Email: <span className='color-main'>info@swayprotocol.org</span>, attention it to the &quot;Data Privacy Officer&quot;.</p>
            <p>12.2 In the event of a complaint, please set out the cause of your complaint, how you would like us to resolve the complaint and any other information you believe to be relevant. A customer complaints officer (&quot;Officer&quot;) will consider your complaint. The Officer will consider your complaint without prejudice based on the information you have provided, and any information provided by Sway Protocol.</p>
            <p>12.3 Within 15 business days of our receipt of your complaint the Officer will address all points raised in your complaint by sending you an email in which the Officer will: (i) offer to resolve your complaint in the way your requested; (ii) make a determination rejecting your complaint and set out the reasons for the rejection; or (iii) offer to resolve your complaint with an alternative solution. In exceptional circumstances, if the Officer is unable to respond to your complaint within 15 business days for reasons beyond Sway Protocol’s control, the Officer will send you a holding reply indicating the reasons for a delay in answering your complaint and specifying the deadline by which the Officer will respond to your complaint (which will be no later than 30 business days from our receipt of your complaint).</p>
            <p>12.4 Any offer of resolution made to you will only become binding on us if accepted by you. An offer of resolution will not constitute any admission by us of any wrongdoing or liability regarding the subject matter of the complaint.</p>
          </div>
          <div className='article'>
            <h4>13. Governing Law and Jurisdiction</h4>
            <p>13.1 These Terms are governed by international laws and subject to the non-exclusive jurisdiction of the courts for any suit, action or proceeding arising out of these Terms.</p>
            <p>13.2 If it has not been possible to resolve a dispute through the dispute process set out above, any dispute arising out of or in connection with this Agreement, including any question regarding the existence, validity or termination of this Agreement, shall be referred to and finally resolved by arbitration under the Arbitration Rules of the International Arbitration Centre, which are deemed to be incorporated by reference into this Section.</p>
            <p>13.3 The tribunal shall consist of three arbitrators. The place and seat of the arbitration shall be London, UK. The language to be used in the arbitration proceedings will be English. The decision of the arbitrators will be final, binding and enforceable against you and us, and a judgment upon any award rendered by the arbitrators may be entered in any court having jurisdiction. In no event will the arbitrators have the authority to make any award that provides for punitive or exemplary damages.</p>
          </div>
          <div className='article'>
            <h4>14. Data Protection</h4>
            <p>You acknowledge that we may process personal data in relation to you (if you are an individual), and personal data that you have provided (or in the future provide) to us in relation to your employees and other associated, or other individuals (if you not an individual), in connection with this Agreement, or the services. We will process this personal data in accordance with the Privacy Policy. Accordingly, you represent and warrant that: a. your disclosure to us of any personal data relating to individuals other than yourself was or will be made in accordance with all applicable data protection and data privacy laws, and those data are accurate, up to date and relevant when disclosed; b. before providing any such personal data to us, you acknowledge that you have read and understood our Privacy Policy, and, in the case of personal data relating to an individual other than yourself, have (or will at the time of disclosure have) provided the individual with a copy of, or directed the individual towards a webpage containing that Privacy Policy (as amended from time to time); and c. if from time to time we provide you with a replacement version of the Privacy Policy, you will promptly read that notice and provide updated copies of the Privacy Policy to, or re-direct towards a webpage containing the updated Privacy Policy, any individual whose personal data you have provided to us.</p>
          </div>
          <div className='article'>
            <h4>17. Miscellaneous</h4>
            <p>17.1 This Agreement (including documents incorporated by reference herein) comprise the entire understanding and agreement between you and Sway Protocol as to the subject matter hereof, and it supersedes any and all prior discussions, agreements and understandings of any kind (including without limitation any prior versions of this Agreement), and every nature between and among you and Sway Protocol.</p>
            <p>17.2 This Agreement is personal to you and you cannot transfer or assign your rights, licenses, interests and/or obligations to anyone else. We may transfer or assign our rights licenses, interests and / or our obligations at any time, including as part of a merger, acquisition or other corporate reorganisation involving Sway Protocol, provided that this transfer or assignment does not materially impact the quality of the services you receive. Subject to the foregoing, this Agreement will bind and inure to the benefit of the parties, their successors and permitted assigns.</p>
            <p>17.3 If any provision of this Agreement is determined to be invalid or unenforceable under any applicable law, this will not affect the validity of any other provision. If any provision is found unenforceable, the unenforceable provision will be severed, and the remaining provisions will be enforced.</p>
            <p>17.4 We may not always strictly enforce our rights under this Agreement. If we do choose not to enforce our rights at any time, this is a temporary measure and we may enforce our rights strictly again at any time.</p>
            <p>17.5 This Agreement and any information or notifications that you or we are to provide should be in English. Any translation of this Agreement or other documents is provided for your convenience only and may not accurately represent the information in the original English. In the event of any inconsistency, the English language version of this Agreement or other documents shall prevail.</p>
            <p>17.6 In the event that Sway Protocol is acquired by or merged with a third party entity, we reserve the right, in any of these circumstances, to transfer or assign the information we have collected from you and our relationship with you (including this Agreement) as part of such merger, acquisition, sale, or other change of control.</p>
            <p>17.7 All provisions of this Agreement which by their nature extend beyond the expiration or termination of this Agreement, including, without limitation, the Sections relating to suspension or termination, Sway Protocol Account cancellation, debts owed to Sway Protocol, general use of the Sites, disputes with Sway Protocol, and general provisions will continue to be binding and operate after the termination or expiration of this Agreement.</p>
          </div>
        </div>
      </div>
    </div>
  </section>
);

